# Generated by Django 2.2.19 on 2022-06-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('phone', models.CharField(default='', max_length=32, unique=True, verbose_name='手机号')),
                ('country_id', models.IntegerField(default=0, verbose_name='国家id')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(default='', max_length=120, unique=True, verbose_name='邮箱地址')),
                ('create_time', models.IntegerField(default=0, verbose_name='创建时间')),
                ('update_time', models.IntegerField(default=0, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
